apiVersion: skaffold/v3
kind: Config
metadata:
  name: tickets-poc
build:
  artifacts:
    - image: tickets-poc/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: tickets-poc/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: tickets-poc/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: tickets-poc/orders
      context: orders
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/tickets-depl.yaml
    - infra/k8s/tickets-mongo-depl.yaml
    - infra/k8s/nats-depl.yaml
    - infra/k8s/orders-depl.yaml
    - infra/k8s/orders-mongo-depl.yaml
